### ISSUE TITLE
Stops working with new Radarr v4

### ISSUE THREAD

**Issue by AliceDmaus** [saltydk/Plex-Match-Fixer#4]
Hey

Sadly it doesnt work anymore since the stable Update to Radarr v4.
In the changelog i see:
- Remove Legacy API

I hope the project is not dead because i like it :)

**Comment by saltydk** [comment]
What error are you getting?

**Comment by AliceDmaus** [comment]
`01 Feb 2022 08:24:09 - Loading data from Sonarr instances:                       100%|███████████████████████████████████████████████████████████████████|   2  /  2   [    4 s]

01 Feb 2022 08:24:13 - Loading data from Radarr instances:                         0%|                                                                   |   0  /  2   [    0 s]

Traceback (most recent call last):
  File "app.py", line 82, in <module>
    "movie").data
  File "/opt/matcharr/classes/arr.py", line 8, in __init__
    self.data = json.loads(r.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by saltydk** [comment]
I'll have a look when I am back at my PC.

**Comment by AliceDmaus** [comment]
Sorry, my mistake, u can close the issue. Used an old matcharr version, didnt saw u updated it 2 months ago.
Its back working :)

**Comment by saltydk** [comment]
Fair enough.
